# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\1st_backup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quanlyphongmay(object):
    def setupUi(self, quanlyphongmay):
        quanlyphongmay.setObjectName("quanlyphongmay")
        quanlyphongmay.resize(1400, 800)
        self.centralwidget = QtWidgets.QWidget(quanlyphongmay)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color:#0F172A;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_frame = QtWidgets.QFrame(self.centralwidget)
        self.sidebar_frame.setMinimumSize(QtCore.QSize(230, 230))
        self.sidebar_frame.setStyleSheet("QFrame#sidebar_frame{\n"
"    background-color: #111827;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}")
        self.sidebar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar_frame.setObjectName("sidebar_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar_frame)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.sidebar_frame)
        self.label.setStyleSheet("color: white;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"padding: 20px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_dashboard = QtWidgets.QPushButton(self.sidebar_frame)
        self.btn_dashboard.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding: 14px;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #374151;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #2563EB;\n"
"}")
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.verticalLayout.addWidget(self.btn_dashboard)
        self.btn_computers = QtWidgets.QPushButton(self.sidebar_frame)
        self.btn_computers.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding: 14px;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #374151;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #2563EB;\n"
"}")
        self.btn_computers.setObjectName("btn_computers")
        self.verticalLayout.addWidget(self.btn_computers)
        self.btn_monitor = QtWidgets.QPushButton(self.sidebar_frame)
        self.btn_monitor.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding: 14px;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #374151;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #2563EB;\n"
"}\n"
"")
        self.btn_monitor.setObjectName("btn_monitor")
        self.verticalLayout.addWidget(self.btn_monitor)
        self.btn_files = QtWidgets.QPushButton(self.sidebar_frame)
        self.btn_files.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding: 14px;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #374151;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #2563EB;\n"
"}")
        self.btn_files.setObjectName("btn_files")
        self.verticalLayout.addWidget(self.btn_files)
        self.btn_settings = QtWidgets.QPushButton(self.sidebar_frame)
        self.btn_settings.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding: 14px;\n"
"    border-radius: 10px;\n"
"    font-size: 15px;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #374151;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #2563EB;\n"
"}")
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout.addWidget(self.btn_settings)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.sidebar_frame)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topbar_frame = QtWidgets.QFrame(self.main_frame)
        self.topbar_frame.setMinimumSize(QtCore.QSize(70, 70))
        self.topbar_frame.setStyleSheet("QFrame#topbar_frame{\n"
"    background-color: #111827;\n"
"    border-radius: 15px;\n"
"}")
        self.topbar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar_frame.setObjectName("topbar_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topbar_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_page_title = QtWidgets.QLabel(self.topbar_frame)
        self.label_page_title.setStyleSheet("color:white;\n"
"font-size:24px;\n"
"font-weight:bold;\n"
"padding-left:15px;")
        self.label_page_title.setObjectName("label_page_title")
        self.horizontalLayout_2.addWidget(self.label_page_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_refresh = QtWidgets.QPushButton(self.topbar_frame)
        self.btn_refresh.setStyleSheet("QPushButton{\n"
"    background-color:#2563EB;\n"
"    color:white;\n"
"    padding:10px 18px;\n"
"    border-radius:10px;\n"
"    font-size:14px;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3B82F6;\n"
"}")
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_2.addWidget(self.btn_refresh)
        self.verticalLayout_3.addWidget(self.topbar_frame)
        self.main_stacked_widget = QtWidgets.QStackedWidget(self.main_frame)
        self.main_stacked_widget.setObjectName("main_stacked_widget")
        self.page_dashboard = QtWidgets.QWidget()
        self.page_dashboard.setObjectName("page_dashboard")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_dashboard)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cards_container = QtWidgets.QFrame(self.page_dashboard)
        self.cards_container.setEnabled(True)
        self.cards_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cards_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cards_container.setObjectName("cards_container")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.cards_container)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 15)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.card_online = QtWidgets.QFrame(self.cards_container)
        self.card_online.setMinimumSize(QtCore.QSize(0, 120))
        self.card_online.setStyleSheet("QFrame#card_online{\n"
"    background-color:#374151;\n"
"    border-radius:20px;\n"
"}")
        self.card_online.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_online.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card_online.setObjectName("card_online")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.card_online)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.card_online)
        self.label_8.setStyleSheet("color:#D1D5DB;\n"
"font-size:16px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.label_online_count = QtWidgets.QLabel(self.card_online)
        self.label_online_count.setStyleSheet("color:white;\n"
"font-size:40px;\n"
"font-weight:bold;")
        self.label_online_count.setObjectName("label_online_count")
        self.verticalLayout_7.addWidget(self.label_online_count)
        self.horizontalLayout_4.addWidget(self.card_online)
        self.card_offline = QtWidgets.QFrame(self.cards_container)
        self.card_offline.setMinimumSize(QtCore.QSize(0, 120))
        self.card_offline.setStyleSheet("QFrame#card_offline{\n"
"    background-color:#EF4444;\n"
"    border-radius:20px;\n"
"}")
        self.card_offline.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card_offline.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card_offline.setObjectName("card_offline")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.card_offline)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.card_offline)
        self.label_4.setStyleSheet("color:#D1D5DB;\n"
"font-size:16px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.label_offline_count = QtWidgets.QLabel(self.card_offline)
        self.label_offline_count.setStyleSheet("font-size:36px;\n"
"font-weight:bold;\n"
"color:white;\n"
"\n"
"")
        self.label_offline_count.setObjectName("label_offline_count")
        self.verticalLayout_9.addWidget(self.label_offline_count)
        self.horizontalLayout_4.addWidget(self.card_offline)
        self.verticalLayout_4.addWidget(self.cards_container)
        self.tableWidget = QtWidgets.QTableWidget(self.page_dashboard)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color:#1F2937;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    gridline-color:#374151;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color:#111827;\n"
"    color:white;\n"
"    padding:10px;\n"
"    border:none;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    padding:10px;\n"
"}\n"
"\n"
"QTableWidget::item:selected{\n"
"    background-color:#2563EB;\n"
"}")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.main_stacked_widget.addWidget(self.page_dashboard)
        self.page_computers = QtWidgets.QWidget()
        self.page_computers.setObjectName("page_computers")
        self.computers_scroll = QtWidgets.QScrollArea(self.page_computers)
        self.computers_scroll.setGeometry(QtCore.QRect(10, 10, 1071, 601))
        self.computers_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.computers_scroll.setWidgetResizable(True)
        self.computers_scroll.setObjectName("computers_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1071, 601))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.computer_card = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.computer_card.setMinimumSize(QtCore.QSize(250, 170))
        self.computer_card.setMaximumSize(QtCore.QSize(250, 170))
        self.computer_card.setStyleSheet("QFrame#computer_card{\n"
"    background-color:#1F2937;\n"
"    border-radius:20px;\n"
"}")
        self.computer_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.computer_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.computer_card.setObjectName("computer_card")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.computer_card)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.computer_card)
        self.label_3.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"font-weight:bold;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.computer_card)
        self.label_5.setStyleSheet("color:#D1D5DB;\n"
"font-size:13px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.computer_card)
        self.label_6.setStyleSheet("color:#22C55E;\n"
"font-size:14px;\n"
"font-weight:bold;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.computer_card)
        self.label_7.setStyleSheet("color:#9CA3AF;\n"
"font-size:13px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.computer_card)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:#2563EB;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    padding:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3B82F6;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.gridLayout_2.addWidget(self.computer_card, 0, 0, 1, 1)
        self.computers_scroll.setWidget(self.scrollAreaWidgetContents)
        self.main_stacked_widget.addWidget(self.page_computers)
        self.page_monitor = QtWidgets.QWidget()
        self.page_monitor.setObjectName("page_monitor")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_monitor)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.monitor_scroll = QtWidgets.QScrollArea(self.page_monitor)
        self.monitor_scroll.setWidgetResizable(True)
        self.monitor_scroll.setObjectName("monitor_scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1073, 602))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.monitor_card = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.monitor_card.setStyleSheet("QFrame#monitor_card{\n"
"    background-color:#111827;\n"
"    border-radius:20px;\n"
"    border:1px solid #374151;\n"
"}")
        self.monitor_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.monitor_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.monitor_card.setObjectName("monitor_card")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.monitor_card)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.monitor_card)
        self.label_15.setMinimumSize(QtCore.QSize(100, 50))
        self.label_15.setStyleSheet("color:white;\n"
"font-size:22px;\n"
"font-weight:bold;\n"
"padding-left:10px;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.monitor_card)
        self.label_16.setMinimumSize(QtCore.QSize(300, 175))
        self.label_16.setStyleSheet("background-color:#1F2937;\n"
"border-radius:15px;\n"
"color:#6B7280;\n"
"font-size:20px;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.btn_shutdown = QtWidgets.QPushButton(self.monitor_card)
        self.btn_shutdown.setStyleSheet("QPushButton{\n"
"    background-color:#DC2626;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius:12px;\n"
"    padding:14px;\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#EF4444;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#B91C1C;\n"
"}")
        self.btn_shutdown.setObjectName("btn_shutdown")
        self.verticalLayout_10.addWidget(self.btn_shutdown)
        self.gridLayout.addWidget(self.monitor_card, 0, 0, 1, 1)
        self.monitor_scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.monitor_scroll)
        self.main_stacked_widget.addWidget(self.page_monitor)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.label_19 = QtWidgets.QLabel(self.page_settings)
        self.label_19.setGeometry(QtCore.QRect(310, 220, 55, 16))
        self.label_19.setObjectName("label_19")
        self.main_stacked_widget.addWidget(self.page_settings)
        self.page_files = QtWidgets.QWidget()
        self.page_files.setObjectName("page_files")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_files)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clients_frame = QtWidgets.QFrame(self.page_files)
        self.clients_frame.setStyleSheet("QFrame#clients_frame{\n"
"    background-color:#111827;\n"
"    border-radius:15px;\n"
"}")
        self.clients_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clients_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clients_frame.setObjectName("clients_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.clients_frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.clients_frame)
        self.label_17.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"font-weight:bold;\n"
"padding:10px;")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.list_clients = QtWidgets.QListWidget(self.clients_frame)
        self.list_clients.setStyleSheet("QListWidget{\n"
"    background-color:#1E293B;\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:white;\n"
"    padding:8px;\n"
"    font-size:14px;\n"
"}\n"
"\n"
"QListWidget::item{\n"
"    background-color:#0F172A;\n"
"    border-radius:10px;\n"
"    padding:12px;\n"
"    margin-bottom:8px;\n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    background-color:#2563EB;\n"
"}\n"
"\n"
"QListWidget::item:hover{\n"
"    background-color:#334155;\n"
"}")
        self.list_clients.setObjectName("list_clients")
        self.verticalLayout_11.addWidget(self.list_clients)
        self.horizontalLayout_3.addWidget(self.clients_frame)
        self.sendfile_frame = QtWidgets.QFrame(self.page_files)
        self.sendfile_frame.setStyleSheet("QFrame#sendfile_frame{\n"
"    background-color:#111827;\n"
"    border-radius:15px;\n"
"}")
        self.sendfile_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendfile_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendfile_frame.setObjectName("sendfile_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.sendfile_frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.sendfile_frame)
        self.label_18.setStyleSheet("color:white;\n"
"font-size:22px;\n"
"font-weight:bold;\n"
"padding:10px;")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.frame = QtWidgets.QFrame(self.sendfile_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_file_path = QtWidgets.QLineEdit(self.frame)
        self.line_file_path.setStyleSheet("QLineEdit{\n"
"    background-color:#1F2937;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    padding:12px;\n"
"    color:white;\n"
"    font-size:14px;\n"
"}")
        self.line_file_path.setObjectName("line_file_path")
        self.horizontalLayout_5.addWidget(self.line_file_path)
        self.btn_choose_file = QtWidgets.QPushButton(self.frame)
        self.btn_choose_file.setStyleSheet("QPushButton{\n"
"    background-color:#374151;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    padding:12px;\n"
"    font-size:14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#4B5563;\n"
"}")
        self.btn_choose_file.setObjectName("btn_choose_file")
        self.horizontalLayout_5.addWidget(self.btn_choose_file)
        self.verticalLayout_12.addWidget(self.frame)
        self.progress_send = QtWidgets.QProgressBar(self.sendfile_frame)
        self.progress_send.setStyleSheet("QProgressBar{\n"
"    background-color:#1F2937;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    text-align:center;\n"
"    color:white;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background-color:#2563EB;\n"
"    border-radius:10px;\n"
"}")
        self.progress_send.setProperty("value", 0)
        self.progress_send.setObjectName("progress_send")
        self.verticalLayout_12.addWidget(self.progress_send)
        self.btn_send_file = QtWidgets.QPushButton(self.sendfile_frame)
        self.btn_send_file.setStyleSheet("QPushButton{\n"
"    background-color:#2563EB;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    padding:14px;\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3B82F6;\n"
"}")
        self.btn_send_file.setObjectName("btn_send_file")
        self.verticalLayout_12.addWidget(self.btn_send_file)
        self.btn_getfiles = QtWidgets.QPushButton(self.sendfile_frame)
        self.btn_getfiles.setStyleSheet("QPushButton{\n"
"    background-color:#2563EB;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    padding:14px;\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#3B82F6;\n"
"}")
        self.btn_getfiles.setObjectName("btn_getfiles")
        self.verticalLayout_12.addWidget(self.btn_getfiles)
        self.text_log = QtWidgets.QTextEdit(self.sendfile_frame)
        self.text_log.setStyleSheet("QTextEdit{\n"
"    background-color:#1F2937;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    color:#D1D5DB;\n"
"    padding:10px;\n"
"    font-size:13px;\n"
"}")
        self.text_log.setReadOnly(True)
        self.text_log.setObjectName("text_log")
        self.verticalLayout_12.addWidget(self.text_log)
        self.horizontalLayout_3.addWidget(self.sendfile_frame)
        self.main_stacked_widget.addWidget(self.page_files)
        self.verticalLayout_3.addWidget(self.main_stacked_widget)
        self.horizontalLayout.addWidget(self.main_frame)
        quanlyphongmay.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(quanlyphongmay)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 26))
        self.menubar.setObjectName("menubar")
        quanlyphongmay.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(quanlyphongmay)
        self.statusbar.setObjectName("statusbar")
        quanlyphongmay.setStatusBar(self.statusbar)

        self.retranslateUi(quanlyphongmay)
        self.main_stacked_widget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(quanlyphongmay)

    def retranslateUi(self, quanlyphongmay):
        _translate = QtCore.QCoreApplication.translate
        quanlyphongmay.setWindowTitle(_translate("quanlyphongmay", "MainWindow"))
        self.label.setText(_translate("quanlyphongmay", "💻 PHÒNG MÁY"))
        self.btn_dashboard.setText(_translate("quanlyphongmay", "🏠 Dashboard"))
        self.btn_computers.setText(_translate("quanlyphongmay", "🖥 Máy tính"))
        self.btn_monitor.setText(_translate("quanlyphongmay", "🎮 Điều khiển"))
        self.btn_files.setText(_translate("quanlyphongmay", "📁 File"))
        self.btn_settings.setText(_translate("quanlyphongmay", "⚙ Cài đặt"))
        self.label_page_title.setText(_translate("quanlyphongmay", "Dashboard"))
        self.btn_refresh.setText(_translate("quanlyphongmay", "⟳ Refresh"))
        self.label_8.setText(_translate("quanlyphongmay", "Máy Online"))
        self.label_online_count.setText(_translate("quanlyphongmay", "TextLabel"))
        self.label_4.setText(_translate("quanlyphongmay", "Máy offline"))
        self.label_offline_count.setText(_translate("quanlyphongmay", "TextLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("quanlyphongmay", "Tên máy"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("quanlyphongmay", "IP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("quanlyphongmay", "Trạng thái"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("quanlyphongmay", "Ping"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("quanlyphongmay", "Điều khiển"))
        self.label_3.setText(_translate("quanlyphongmay", "PC-01"))
        self.label_5.setText(_translate("quanlyphongmay", "192.168.1.10"))
        self.label_6.setText(_translate("quanlyphongmay", "● Online"))
        self.label_7.setText(_translate("quanlyphongmay", "Ping: 12 ms"))
        self.pushButton.setText(_translate("quanlyphongmay", "PushButton"))
        self.label_15.setText(_translate("quanlyphongmay", "🖥 PC-01"))
        self.label_16.setText(_translate("quanlyphongmay", "Live screen preview"))
        self.btn_shutdown.setText(_translate("quanlyphongmay", "⛔ Tắt máy"))
        self.label_19.setText(_translate("quanlyphongmay", "setting"))
        self.label_17.setText(_translate("quanlyphongmay", "Danh sách máy"))
        self.label_18.setText(_translate("quanlyphongmay", "Gửi file đến máy client"))
        self.line_file_path.setText(_translate("quanlyphongmay", "Chưa chọn file..."))
        self.btn_choose_file.setText(_translate("quanlyphongmay", "📂 Chọn file"))
        self.btn_send_file.setText(_translate("quanlyphongmay", "🚀 Gửi file"))
        self.btn_getfiles.setText(_translate("quanlyphongmay", "Nhận file"))
